### ISSUE TITLE
PartialUnification

### ISSUE THREAD

**Issue by nbenns** [calvinlfer/free-monad-coproduct-example#1]
You shouldn't need that patch for Scala, its enabled in 2.11 with -Ypartial-unification.
see https://github.com/milessabin/si2712fix-plugin

**Comment by calvinlfer** [comment]
I thought that you could only use `-Ypartial-unification` if you used [Typelevel Scala](https://github.com/typelevel/scala) at least in 2.11.8

**Comment by calvinlfer** [comment]
Looking at [this](https://github.com/milessabin/si2712fix-plugin#usage), it seems we have to wait for 2.11.9

**Comment by calvinlfer** [comment]
Fixed by https://github.com/calvinlfer/free-monad-coproduct-example/commit/993eee9ba3607f394fd0da15309c5e6b6cd8c787
